### PR TITLE
Dev-only CLI

### PR DESCRIPTION
**Pull request by kddnewton**
We keep adding more scripts to /bin that are doing the same kinds of processing. Instead, this commit consolidates them all into a single CLI that shares the same logic so that we can consistently read files in the same way.

It keeps around 2 binstubs for bin/lex and bin/parse since those are the most used and I'm sure people have built up muscle memory for those. Those scripts are now just wrappers for forwarding to bin/prism.

### CODE REVIEW

**Review by noahgibbs — APPROVED** [review]

**Comment by noahgibbs** [comment]
Seems like a good idea.

**Comment by enebo** [comment]
@kddnewton Is there a possibility of us making a non-dev script so we can run and generate AST, etc... from the installed gem?

**Comment by kddnewton** [comment]
Yeah we could do that. I don't think CRuby will want us to ship that with it so we'll need to take a little care to make sure it doesn't get copied over, but that's doable. Could you open an issue for it?

**Comment by enebo** [comment]
@noahgibbs I added https://github.com/jruby/jruby/issues/8094 for that newly discovered ripper issue.

**Comment by kddnewton** [comment]
@enebo if you have CRuby 3.3, you can run `ruby --dump=prism -e 'whatever'` and you'll get the AST.

**Comment by enebo** [comment]
@kddnewton Yeah that works for MRI for sure.  I have thought about adding similar thing to JRuby but have a bin/ast (which only currently works for legacy parser).

**Comment by eregon** [comment]
It'd be quite convenient to have an executable, because that would then use the installed gem vs the version used in CRuby at CRuby build time.
I think it would make sense to add a `prism` or so executable to CRuby too, because it does ship Prism as a default gem so it should be consistent (it's same for e.g. rdoc).

**Pull request merged**
