### PR TITLE
Add SPLAT flag on ArrayNode indicating if it contains splat element(s)

### LINKED ISSUE #1680: Add a flag to Arrays which contain a single splat element
At parse time, we know if an array only has a single splat element. This compiles differently. Instead of having to recompute this information at compile time, we can add it as a flag on an ArrayNode so it's known earlier.

### LINKED ISSUE #1896: [COMPILER] Stack underflow using splat assignment
Minimal repro to get stack underflow:

```
a, *b = *c
1
```

This seems to be an issue even not in the "popped" case in that the instructions look wrong for even `*b = *c`

I found this running this code 

` RUBY_ISEQ_DUMP_DEBUG=prism make test-all TESTS=../test/-ext-/tracepoint/test_tracepoint.rb`

### PR DESCRIPTION
**Pull request by jemmaissroff**
This commit puts a SPLAT flag on any ArrayNodes which contain SplatNode elements

Closes #1680, also helps close #1896

### CODE REVIEW

**Review by kddnewton — APPROVED** [review]
Looks good

**Comment by kddnewton** [comment]
Actually, could you call it `CONTAINS_SPLAT`? Thinking about it it looks like it might mean "this array is splatted" not necessarily that it has one inside

**Comment by jemmaissroff** [comment]
> Actually, could you call it `CONTAINS_SPLAT`? Thinking about it it looks like it might mean "this array is splatted" not necessarily that it has one inside

Sure, do you want me to change the ArgumentsNodeFlag to `CONTAINS_KEYWORD_SPLAT` too then? I also liked `CONTAINS_SPLAT` better, but thought it was best to be consistent.

Also just confirming - that Ruby test-all failure is fine and the bug still exists there on not templating?

**Comment by kddnewton** [comment]
Yeah `CONTAINS_KEYWORD_SPLAT` would be better now that you mention it and I see it with this context.

The test-all suite is fine, something isn't rebuilding properly, I'm not sure what it is.

**Review by kddnewton — APPROVED** [review]

**Comment by jemmaissroff** [comment]
Waiting until https://github.com/ruby/ruby/pull/8987 merges before merging this PR

**Comment by eregon** [comment]
Given I have already rebased https://github.com/ruby/prism/pull/1891 2-3 times, I'd appreciate if we'd merge that first.
Plus, it would fix the test-all CI check.

**Comment by jemmaissroff** [comment]
> Given I have already rebased #1891 2-3 times, I'd appreciate if we'd merge that first. Plus, it would fix the test-all CI check.

I'm going to merge this and then will rebase your branch! I don't want to override a different review, and this is currently blocking for me. Seems like it's either that I'd wait and then rebase this, or can rebase yours directly

**Comment by eregon** [comment]
That works, thanks!

**Pull request merged**
