### PR TITLE
Use ENV CC if present when compiling

### PR DESCRIPTION
**Pull request by kddnewton**
Trying to determine if this fixes ppc64le problems

### CODE REVIEW

**Comment by kddnewton** [comment]
@junaruga unfortunately it looks like maybe this doesn't fix it? Maybe I need to specify the compiler in the travis config somehow?

**Comment by kddnewton** [comment]
Closing for now

**Comment by junaruga** [comment]
> @junaruga unfortunately it looks like maybe this doesn't fix it? Maybe I need to specify the compiler in the travis config somehow?

Yes, the code in this PR is not enough to fix the issue. If you want to set the same compiler gcc-11 used in the ruby/ruby in the ppc64le, first you need to download the gcc-11 deb package, then you need to set a specific compiler `CC=gcc-11` somewhere in the `.travis.yml`.

The following code in the `language: c` mode means `export CC=gcc-11`.

https://github.com/ruby/ruby/blob/master/.travis.yml#L42
```
compiler: gcc-11
```

**Comment by junaruga** [comment]
Below is an example. 
https://github.com/ruby/prism/pull/2387

**Comment by junaruga** [comment]
I rebased the #2387 to use gcc-11. Sorry a way to modify the `extconf.rb` to set a specific C compiler didn't work. But I found another way.

**Pull request closed without merging**
