### PR TITLE
Provide Parameters#signature for mirroring Method#parameters

### PR DESCRIPTION
**Pull request by kddnewton**
Nice to have for client libraries.

@seven1m I thought you might be able to use this to implement `Method#parameters`

### CODE REVIEW

**Review by seven1m — COMMENTED** [review]
Whoa, sweet! 😍

**Comment by kddnewton** [comment]
@eregon had to turn off truffleruby for this test because it found a bunch of incompatibilities. You can see the run here: https://github.com/ruby/prism/actions/runs/6779285735/job/18426147329?pr=1777

**Comment by eregon** [comment]
Right, makes sense. cc @andrykonchin
Copying it here for convenience:
```
===============================================================================
Failure: test_block_anonymous(Prism::ParametersSignatureTest)
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:79:in `assert_parameters'
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:66:in `test_block_anonymous'
     63:     end
     64: 
     65:     def test_block_anonymous
  => 66:       assert_parameters([[:block, :&]], "&")
     67:     end
     68: 
     69:     def test_forwarding
<internal:core> core/throw_catch.rb:36:in `catch'
<internal:core> core/throw_catch.rb:36:in `catch'
<[[:block, :&]]> expected but was
<[[:block, :"%forward_block"]]>

diff:
? [[:block, :&               ]]
?            "%forward_block"  
?            ?  
===============================================================================
===============================================================================
Failure: test_forwarding(Prism::ParametersSignatureTest)
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:79:in `assert_parameters'
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:70:in `test_forwarding'
     67:     end
     68: 
     69:     def test_forwarding
  => 70:       assert_parameters([[:rest, :*], [:keyrest, :**], [:block, :&]], "...")
     71:     end
     72: 
     73:     private
<internal:core> core/throw_catch.rb:36:in `catch'
<internal:core> core/throw_catch.rb:36:in `catch'
<[[:rest, :*], [:keyrest, :**], [:block, :&]]> expected but was
<[[:rest, :"%forward_rest"],
 [:keyrest, :"%forward_kwrest"],
 [:block, :"%forward_block"]]>

diff:
? [[:rest, :*], [:key rest, :**], [:block, :&]]
?           "%forward_    "                    
?           ?????????    ?????      --------------
+  [:keyrest, :"%forward_kwrest"],
+  [:block, :"%forward_block"]]
===============================================================================
===============================================================================
Failure: test_key_ordering(Prism::ParametersSignatureTest)
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:79:in `assert_parameters'
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:58:in `test_key_ordering'
     55:     end
     56: 
     57:     def test_key_ordering
  => 58:       assert_parameters([[:keyreq, :a], [:keyreq, :b], [:key, :c], [:key, :d]], "a:, c: 1, b:, d: 2")
     59:     end
     60: 
     61:     def test_block
<internal:core> core/throw_catch.rb:36:in `catch'
<internal:core> core/throw_catch.rb:36:in `catch'
<[[:keyreq, :a], [:keyreq, :b], [:key, :c], [:key, :d]]> expected but was
<[[:keyreq, :a], [:key, :c], [:keyreq, :b], [:key, :d]]>

diff:
? [[:keyreq, :a], [:key, :c], [:keyreq, :b], [:key, :c], [:key, :d]]
===============================================================================
===============================================================================
Failure: test_keyrest_anonymous(Prism::ParametersSignatureTest)
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:79:in `assert_parameters'
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:54:in `test_keyrest_anonymous'
     51:     end
     52: 
     53:     def test_keyrest_anonymous
  => 54:       assert_parameters([[:keyrest, :**]], "**")
     55:     end
     56: 
     57:     def test_key_ordering
<internal:core> core/throw_catch.rb:36:in `catch'
<internal:core> core/throw_catch.rb:36:in `catch'
<[[:keyrest, :**]]> expected but was
<[[:keyrest, :"%kwrest"]]>

diff:
? [[:keyrest, :**       ]]
?              "%kwrest"  
?              ??  
===============================================================================
===============================================================================
Failure: test_nokey(Prism::ParametersSignatureTest)
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:79:in `assert_parameters'
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:50:in `test_nokey'
     47:     end
     48: 
     49:     def test_nokey
  => 50:       assert_parameters([[:nokey]], "**nil")
     51:     end
     52: 
     53:     def test_keyrest_anonymous
<internal:core> core/throw_catch.rb:36:in `catch'
<internal:core> core/throw_catch.rb:36:in `catch'
<[[:nokey]]> expected but was
<[[:keyrest, :"%nil_kwrest"]]>

diff:
? [[:nokeyrest, :"%nil_kwrest"]]
===============================================================================
===============================================================================
Failure: test_rest_anonymous(Prism::ParametersSignatureTest)
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:79:in `assert_parameters'
/home/runner/work/prism/prism/test/prism/parameters_signature_test.rb:26:in `test_rest_anonymous'
     23:     end
     24: 
     25:     def test_rest_anonymous
  => 26:       assert_parameters([[:rest, :*]], "*")
     27:     end
     28: 
     29:     def test_post
<internal:core> core/throw_catch.rb:36:in `catch'
<internal:core> core/throw_catch.rb:36:in `catch'
<[[:rest, :*]]> expected but was
<[[:rest]]>

diff:
? [[:rest, :*]]
===============================================================================
```

**Comment by andrykonchin** [comment]
The `#parameters` method is fixed on TruffleRuby master (not sure how fast dev build will be available).

All the test cases except one now pass on TruffleRuby.

The only failing test:

```ruby
    def test_key_ordering
      assert_parameters([[:keyreq, :a], [:keyreq, :b], [:key, :c], [:key, :d]], "a:, c: 1, b:, d: 2")
    end
```

It checks order of parameters. Not sure if it's documented explicitly so it might be incorrectly to rely on it (and require) in the test.

**Comment by kddnewton** [comment]
Honestly I'm not 100% sure, but I know it's consistent with the calling convention. I think I'd like to keep it for now. Happy to skip just that test on truffleruby though.

**Pull request merged**
