### PR TITLE
Fallback for pm_string_mapped_init

### PR DESCRIPTION
**Pull request by kddnewton**
@hasumikin will this work, or will referencing `FILE` at all break compiling on embedded?

### CODE REVIEW

**Comment by hasumikin** [comment]
@kddnewton
It will break. You can not assume an embedded system has `FILE`.
Some embedded systems have `FILE` but others don't.

Letting users read the entire Ruby script (whether it's a "file" or not) is enough, I think

**Comment by kddnewton** [comment]
@hasumikin unfortunate. I was hoping to provide a fallback for posix platforms that don't have mmap. Do you think checking for either `_POSIX_VERSION` or `_FILE_OFFSET_BITS` would work?

**Comment by hasumikin** [comment]
@kddnewton 
Sorry but I have no idea.
I don't think there is a robust way to know a POSIX that has no MMAP...

**Comment by kddnewton** [comment]
No worries, I'll close this until it becomes a real use-case.

**Pull request closed without merging**
