### PR TITLE
added CP950 encoding

### PR DESCRIPTION
**Pull request by dhavalsingh**
helps https://github.com/ruby/prism/issues/1843

### CODE REVIEW

**Review by kddnewton — APPROVED** [review]

**Comment by dhavalsingh** [comment]
@kddnewton is this a flaky test? sorry a bit new to C. But I can't seem to find any issue. 
I used https://github.com/ruby/prism/pull/1907/files as a reference.

The error msg in the test says
```
/usr/bin/ld: prism/prism.o: in function `parser_lex_magic_comment_encoding_value':
/home/runner/work/prism/prism/ruby/ruby/prism/prism.c:6236: undefined reference to `pm_encoding_cp950'
```

**Comment by dhavalsingh** [comment]
oh, that PR also failed this similar test. Any reason why it's failing and we are okay with it?

**Comment by dhavalsingh** [comment]
Hmm... it failed again. So not a flaky test i guess...
Any idea how to move forward? @eregon

**Comment by eregon** [comment]
No, I think @jemmaissroff or @kddnewton knows better about the integration of Prism in the CRuby build system.

**Comment by dhavalsingh** [comment]
in CRuby cp950 is treated same as Big5 i think, if i am reading this correctly.
https://github.com/ruby/ruby/blob/8e93bf8e1fbac73b677c333b19a8b55ae9daddc3/enc/big5.c#L312C2-L312C31

**Comment by kddnewton** [comment]
Don't worry about it, it's just because it's a new file, so `common.mk` needs to be updated. I'll merge it into CRuby first and then merge this PR.

**Comment by dhavalsingh** [comment]
Yayy, okay! This will be my first contribution to CRuby. 
This is probably TMI, but I've been using Ruby/Rails for the last 3 years and I love it so much. 
Even though this isn't a significant contribution, this PR getting merged will be in my top 5 highlights of this year :')

**Comment by kddnewton** [comment]
Not TMI at all, I'm so happy you were able to contribute! Great work!

**Comment by kddnewton** [comment]
Just waiting on https://github.com/ruby/ruby/pull/9062

**Pull request merged**
