### PR TITLE
Test the generated wasm distribution on Chicory

### PR DESCRIPTION
**Pull request by andreaTP**
Hi all 👋 !
Amazing project 🙂 !

In this PR we produce an unoptimized version of Prism that can be interpreted using the early stage build of [Chicory](https://github.com/dylibso/chicory).
The produced `prism.wasm` artifact is uploaded in CI for easy access.

### CODE REVIEW

**Comment by andreaTP** [comment]
I'll try to fix the CI tomorrow, not really familiar with this process, any help would be welcome 🙏

**Review by kddnewton — APPROVED** [review]
Yeah this looks good.

@enebo are you good with this? Any changes you would want?

**Comment by andreaTP** [comment]
I'm not sure where to start for fixing the `gem-package` issue in CI, any pointer is highly appreciated.

**Comment by kddnewton** [comment]
@andreaTP yeah I just looked into it, it just requires a bump of the version, don't worry about it I'll get it fixed

**Review by kddnewton — APPROVED** [review]

**Pull request merged**
