### PR TITLE
Introduce `PRISM_HAS_MMAP` macro

### PR DESCRIPTION
**Pull request by hasumikin**
This is to know if the memory map interface is available in the target platform by using `_POSIX_MAPPED_FILES` and `_WIN32`

ref #2217

### CODE REVIEW

**Comment by kddnewton** [comment]
@hasumikin I think `_POSIX_MAPPED_FILES` is defined in `unistd.h`, so you probably need to include that before doing the check.

**Comment by hasumikin** [comment]
@kddnewton 
Thank you.
My problem was fixed but another static check error was revealed that I couldn't figure out how to resolve :(

**Comment by kddnewton** [comment]
Thanks @hasumikin you should be able to rebase now and it should be fixed.

My feedback on the PR, is that I think we should keep `PM_STRING_MAPPED` around, even if `PRISM_HAS_MMAP` is false. Maybe we should rename it to `PM_STRING_FILE` or something, but that way we could `malloc` and `read` the file into a `const uint8_t *` the same way you would `mmap` it.

**Comment by kddnewton** [comment]
I'm also happy to make those changes after we merge this if you'd prefer. No problem! 😀

**Comment by hasumikin** [comment]
@kddnewton 

> My feedback on the PR, is that I think we should keep PM_STRING_MAPPED around, even if PRISM_HAS_MMAP is false. Maybe we should rename it to PM_STRING_FILE or something, but that way we could malloc and read the file into a const uint8_t * the same way you would mmap it.

If I didn't get you wrong, we'd better create one in addition to `PM_STRING_MAPPED` and not include `_FILE` because (from the embedded system point of view,) we can not assume we have a filesystem.

How about `PM_STRING_GENERAL` for instance?

```c
/* pm_string.h */
typedef struct {
　(......)
    /** The type of the string. This field determines how the string should be freed. */
    enum {
    　(......)

        /** This string owns its memory, and should be freed using `pm_string_free`. */
        PM_STRING_OWNED,

#ifdef PRISM_HAS_MMAP
        /** This string is a memory-mapped file, and should be freed using `pm_string_free`. */
        PM_STRING_MAPPED,
#endif

        /** This is a general string, and should be taken care of by the user. */
        PM_STRING_GENERAL    // 👈
    } type;
} pm_string_t;
```

**Comment by kddnewton** [comment]
Actually I realize now it should simply return a `PM_STRING_OWNED` if it doesn't have `mmap`, because that's effectively what it is. I'll merge this as-is and see what it takes to do that.

**Comment by kddnewton** [comment]
Thank you for the contribution!

**Review by kddnewton — APPROVED** [review]

**Pull request merged**
